with-expecter: true
disable-version-string: True
packages:
  github.com/davyc98/billing-engine/internal/billing:
    config:
      all: True
      recursive: True
      outpkg: "loanmocks"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: internal/billing/internal/mocks

  github.com/davyc98/billing-engine/internal/pkg:
    config:
      all: True
      recursive: True
      outpkg: "pkgmocks"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: internal/pkg/pkgmocks
